#!/usr/bin/env php
<?php
/**
 * 拾叁网络科技
 * 
 * Date: 2019-02-13
 */

// 站点根目录
define('ROOT_PATH', __DIR__ . '/../');
// 定义项目路径
define('APP_PATH', ROOT_PATH . 'application/');
// 数据绝对路径
define('DATA_PATH', ROOT_PATH . 'data/');
// 运行缓存
define('RUNTIME_PATH', DATA_PATH . 'runtime/');
// 加载框架引导文件
require __DIR__.'/../core/console.php';
